name: Rollback Failure

# If for some reason one of the release workflows failed, rollback and delete release branch

on:
  workflow_call:
    inputs:
      build-path:
        required: true
        type: string

jobs:
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}

    steps:
      - name: Checkout ${{ github.event.repository.name }}
        uses: actions/checkout@v2
        with:
          path: ${{ github.event.repository.name }}
          ref: master

      - name: Extract Maven project version
        run: |
          cd ${{ github.event.repository.name }}/${{ inputs.build-path }}
          echo ::set-output name=project_version::$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
        id: get_version

      - name: Delete branch if created
        uses: dawidd6/action-delete-branch@v3
        with:
          github_token: ${{github.token}}
          branches: release/v${{ steps.get_version.outputs.project_version }}

# What to do next ??