name: Release on GitHub 

# This CD workflow releases packages to GitHub repository AND creates a new release branch
# It only runs on MASTER branch AFTER Build and Test Workflow is completed AND if commit is tagged (which is done when merging previous commits)

on: workflow_call


jobs:
  publish_release:
    runs-on: ubuntu-latest
    name: Publish Release on GitHub

    steps: 
    - name: Checkout ${{ github.event.repository.name }}
      uses: actions/checkout@v2
      with:
        path: ${{ github.event.repository.name }}
        ref: master

    - name: Extract Maven project version
      run: |
        cd ${{ github.event.repository.name }}
        echo ::set-output name=project_version::$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
      id: get_version
        
    # Create new branch and release with artifacts
    - name: Create Release branch
      uses: peterjgrainger/action-create-branch@v2.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        branch: 'release/v${{ steps.get_version.outputs.project_version }}'

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.get_version.outputs.project_version }}
        release_name: RiseClipse ${{ steps.get_version.outputs.project_version }}
        body: This RiseClipse release contains the latest changes available. You can learn more by reading the documentation. Release is created automatically by GH Actions
        draft: false
        prerelease: false
